name: adventofcode2017
version: 1.0.0

dependencies:
  - base

library:
  source-dirs:
    - shared

executables:
  day-01:
    main: Day01/Main.hs
    dependencies:
      - array
  day-02:
    main: Day02/Main.hs
    dependencies:
      - recursion-schemes
  day-03:
    main: Day03/Main.hs
    dependencies:
      - containers
      - lens
  day-04:
    main: Day04/Main.hs
    dependencies:
      - recursion-schemes
  day-05:
    main: Day05/Main.hs
    dependencies:
      - adventofcode2017

ghc-options: -Wall -Werror
