name: adventofcode2017
version: 1.0.0

dependencies:
  - base

library:
  source-dirs:
    - shared
  dependencies:
    - split

executables:
  day-01:
    main: Day01/Main.hs
    dependencies:
      - array
  day-02:
    main: Day02/Main.hs
    dependencies:
      - recursion-schemes
  day-03:
    main: Day03/Main.hs
    dependencies:
      - containers
      - lens
  day-04:
    main: Day04/Main.hs
    dependencies:
      - recursion-schemes
  day-05:
    main: Day05/Main.hs
    dependencies:
      - adventofcode2017
  day-06:
    main: Day06/Main.hs
    dependencies:
      - containers
  day-07:
    main: Day07/Main.hs
    dependencies:
      - containers
      - lens
  day-08:
    main: Day08/Main.hs
    dependencies:
      - containers
      - lens
  day-09:
    main: Day09/Main.hs
    dependencies:
      - parsec
  day-10:
    main: Day10/Main.hs
    dependencies:
      - split
      - adventofcode2017
  day-11:
    main: Day11/Main.hs
    dependencies:
      - split
  day-12:
    main: Day12/Main.hs
    dependencies:
      - containers
      - lens
  day-13:
    main: Day13/Main.hs
  day-14:
    main: Day14/Main.hs
    dependencies:
      - adventofcode2017
      - containers
      - lens
  day-15:
    main: Day15/Main.hs
  day-16:
    main: Day16/Main.hs
    dependencies:
      - containers
      - split
  day-17:
    main: Day17/Main.hs
    dependencies:
      - containers
  day-18:
    main: Day18/Main.hs
    dependencies:
      - containers
      - vector

ghc-options: -Wall -Wwarn
